import { MainLayout } from '@/components/layout';
import Head from 'next/head';
import { NextPageWithLayout } from '../models';
import styles from '../styles/Home.module.css';

const Home: NextPageWithLayout = () => {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        123
      </div>
    </>
  );
};
Home.Layout = MainLayout;
export default Home;
